[package]
name = "xdg-desktop-portal-cosmic"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
anyhow = "1.0.60"
cosmic-protocols = { git = "https://github.com/pop-os/cosmic-protocols" }
cosmic-client-toolkit = { git = "https://github.com/pop-os/cosmic-protocols" }
futures = "0.3"
memmap2 = "0.6.1"
nix = "0.26.2"
# pipewire = { git = "https://github.com/pop-os/pipewire-rs" }
pipewire = { git = "https://gitlab.freedesktop.org/pipewire/pipewire-rs" }
png = "0.17.5"
serde = "1.0.143"
# spa_sys = { package = "libspa-sys", git = "https://github.com/pop-os/pipewire-rs" }
spa_sys = { package = "libspa-sys", git = "https://gitlab.freedesktop.org/pipewire/pipewire-rs" }
tokio = { version = "1.19.2", features = ["macros", "net", "rt", "sync"] }
wayland-client = { version = "0.30.0" }
zbus = { version = "3.13.0", default-features = false, features = ["tokio"] }
